### Send synchronous email
POST http://localhost:8080/emails
Content-Type: application/json

{
    "to": "<any_email_address>",
    "subject": "Test Email",
    "body": "This is a test email."
}

### Get email history
GET http://localhost:8080/emails


### Health Check
GET http://localhost:8080/actuator/health

### Metrics
GET http://localhost:8080/actuator/metrics

### Get memory metrics
GET http://localhost:8080/actuator/metrics/jvm.memory.used

### Get prometheus metrics
GET http://localhost:8080/actuator/prometheus